### ISSUE TITLE
Possibilities of this tool

### ISSUE THREAD

**Issue by RCAPDART** [pamaury/onkyo_teac_tools#1]
Hi!
Great job! 
But is it possible to modify onkyo firmware, "compile" it and update Onkyo DAC-HA300 with it?
Should we wait for RockBox on this device?
Thank you in advance!

**Comment by pamaury** [comment]
Hi, thank you for your interest. To be honest I don't remember much about this, I wrote it for someone who was interested in the onkyo firmware but I don't know if he pursued. There is some info
[here](https://www.rockbox.org/wiki/TEACHAP90SDPort) but as far as I know, no one is actively porting rockbox to this.

**Comment by RCAPDART** [comment]
Hi!
Thank you for your answer! I found this repository from the article which you posted above. 😄
